events {}

http {
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location /api/ {
            proxy_pass http://board-day2-was:5000;
        }
        location /server-board {
            proxy_pass http://board-day2-was:5000;
        }
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
