const created=[],mutated=[],built=[],screens=[];
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
await Promise.all(['Regular','Medium','Bold'].map(style=>figma.loadFontAsync({family:'Noto Sans KR',style})).concat(['Regular','Bold','Semi Bold'].map(style=>figma.loadFontAsync({family:'Inter',style}))));
function box(parent,name,x,y,w,h,color,radius=0){const n=figma.createRectangle();parent.appendChild(n);n.name=name;n.resize(w,h);n.fills=[{type:'SOLID',color:rgb(color)}];n.cornerRadius=radius;n.x=x;n.y=y;created.push(n.id);return n;}
function frame(parent,name,x,y,w,h,color,radius=0){const n=figma.createFrame();parent.appendChild(n);n.name=name;n.resize(w,h);n.fills=color?[{type:'SOLID',color:rgb(color)}]:[];n.cornerRadius=radius;n.clipsContent=true;n.x=x;n.y=y;created.push(n.id);return n;}
function col(parent,name,x,y,w,gap=12){const n=figma.createAutoLayout('VERTICAL');parent.appendChild(n);n.name=name;n.resize(w,1);n.layoutSizingVertical='HUG';n.counterAxisSizingMode='FIXED';n.itemSpacing=gap;n.fills=[];n.x=x;n.y=y;created.push(n.id);return n;}
function row(parent,name,x,y,w,h,gap=16){const n=figma.createAutoLayout('HORIZONTAL');parent.appendChild(n);n.name=name;n.resize(w,h);n.counterAxisSizingMode='FIXED';n.primaryAxisSizingMode='FIXED';n.itemSpacing=gap;n.fills=[];n.x=x;n.y=y;created.push(n.id);return n;}
function text(parent,name,value,size,color,w,weight='Regular',family='Noto Sans KR'){const n=figma.createText();parent.appendChild(n);n.name=name;n.fontName={family,style:weight};n.fontSize=size;n.lineHeight={unit:'PERCENT',value:145};n.characters=value;n.fills=[{type:'SOLID',color:rgb(color)}];n.resize(w,1);n.textAutoResize='HEIGHT';created.push(n.id);return n;}
function label(parent,name,value,size,color,x,y,w,weight='Regular',family='Noto Sans KR'){const n=text(parent,name,value,size,color,w,weight,family);n.x=x;n.y=y;return n;}
function ellipse(parent,name,x,y,w,h,color){const n=figma.createEllipse();parent.appendChild(n);n.name=name;n.resize(w,h);n.fills=[{type:'SOLID',color:rgb(color)}];n.x=x;n.y=y;created.push(n.id);return n;}
function vector(parent,name,data,x,y,color,stroke=null,sw=1){const n=figma.createVector();parent.appendChild(n);n.name=name;n.vectorPaths=[{windingRule:'NONZERO',data}];n.fills=color?[{type:'SOLID',color:rgb(color)}]:[];n.strokes=stroke?[{type:'SOLID',color:rgb(stroke)}]:[];n.strokeWeight=sw;n.x=x;n.y=y;created.push(n.id);return n;}
function section(parent,title,body,w,accent,ink,size=24){const c=col(parent,title,0,0,w,9);text(c,title+' label',title,15,accent,w,'Bold','Inter');text(c,title+' body',body,size,ink,w);return c;}
function slide(name,bg){const s=figma.createSlide();s.name=name;s.fills=[{type:'SOLID',color:rgb(bg)}];created.push(s.id);built.push(s);box(s,'SK signature',0,0,11,1080,'#EA002C');return s;}
function footer(s,url,dark=false){const n=label(s,'GitHub URL',url,17,dark?'#B8C1C8':'#656B73',64,1020,1792,'Regular','Inter');n.hyperlink={type:'URL',value:url};return n;}
function check(){const issues=[];for(const s of built){for(const n of s.children){if(n.x<0||n.y<0||n.x+n.width>1921||n.y+n.height>1081)issues.push({slide:s.id,node:n.id,name:n.name,bounds:[n.x,n.y,n.width,n.height]});}for(const f of s.findAllWithCriteria({types:['FRAME']})){if(!f.clipsContent)continue;const b=f.absoluteBoundingBox;for(const t of f.findAllWithCriteria({types:['TEXT']})){const a=t.absoluteBoundingBox;if(a&&b&&(a.x<b.x-1||a.y<b.y-1||a.x+a.width>b.x+b.width+1||a.y+a.height>b.y+b.height+1))issues.push({slide:s.id,type:'textClip',node:t.id,parent:f.id});}}}return issues;}
