import {projectLinks,githubProfile,portfolioRepository} from './project-links.mjs';
import { aiProjects } from './projects-ai.mjs';
import { productProjects } from './projects-product.mjs';
import { webtoonProject } from './project-webtoon.mjs';
export function makePortfolio(image){
 const slides=[],evidence=[];
 const img=(p,alt,cls='screenshot')=>`<img class="${cls}" src="${image(p)}" alt="${alt}" draggable="false">`;
 const badge=(t,c='')=>`<span class="badge ${c}">${t}</span>`;
 const stats=a=>`<div class="stats">${a.map(v=>`<div class="stat"><small>${v[0]}</small><strong>${v[1]}</strong></div>`).join('')}</div>`;
 const table=(head,rows)=>`<table class="ui-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const flow=a=>`<div class="ui-flow">${a.map(x=>`<b>${x}</b>`).join('<span>→</span>')}</div>`;
 const app=(name,menu,body)=>`<div class="screen-card"><div class="app-chrome"><i></i><i></i><i></i><span>${name.replace(/<[^>]+>/g,'')}</span></div><div class="app">${menu.length?`<div class="app-side"><div class="app-logo">${name}</div>${menu.map((x,i)=>`<div class="app-menu ${i===0?'on':''}">${x}</div>`).join('')}</div>`:''}<div class="app-body">${body}</div></div></div>`;
 const bar=(label,value,width,color='')=>`<div><div class="bar-label"><span>${label}</span><b>${value}</b></div><div class="bar-track"><div class="bar-fill ${color}" style="width:${width}%"></div></div></div>`;
 const tags=a=>`<div class="tags">${a.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`;
 const features=a=>`<div class="feature-strip">${a.map((f,i)=>`<div><span>${['→','↗','✓'][i]}</span><p><b>${f[0]}</b>${f[1]}</p></div>`).join('')}</div>`;
 const storyList=t=>'<ol class="story-list">'+(Array.isArray(t)?t:[t]).map(x=>'<li data-edit>'+x+'</li>').join('')+'</ol>';
 function project(p){const link=projectLinks[p.name];if(!link)throw Error('Missing project link '+p.name);slides.push({name:p.name,preview:p.visual,caption:p.caption,class:p.class||'',html:`<div class="heading"><div><p class="eyebrow">${p.kicker}</p><h2 data-edit>${p.title}</h2><p class="sub" data-edit>${p.subtitle}</p></div><div class="category">${p.category||''}<a class="source-link" contenteditable="false" href="${link.url}" target="_blank" rel="noopener noreferrer">GitHub · 프로젝트 보기 ↗</a></div></div><div class="main-grid"><div class="story"><div class="role" data-edit><b>담당 / 범위</b>${p.role}</div><div class="story-block"><h3>PAIN POINT</h3>${storyList(p.pain)}</div><div class="story-block solution"><h3>SOLUTION</h3>${storyList(p.solution)}</div><div class="takeaway" data-edit>${p.takeaway}</div>${tags(p.tags)}</div><figure class="visual" style="margin:0"><div class="visual-stage ${p.stage||''}">${p.visual}</div><figcaption class="caption">${p.caption}</figcaption></figure></div>${features(p.features)}`});evidence.push({title:p.name,note:p.note||p.caption,files:p.files});}
 slides.push({name:'장현진 포트폴리오',class:'cover',html:`<div class="cover-copy"><p class="eyebrow">AI · DATA · SOFTWARE ENGINEERING</p><h1 data-edit>장현진<br><span>포트폴리오</span></h1><p class="cover-lead" data-edit>질문의 맥락에서 시작해<br>근거 있는 답변과<br>운영 가능한 서비스까지.</p><div class="cover-author" data-edit>P023 장현진<small>RAG · 멀티에이전트 · 모델 튜닝 · 서비스 설계</small></div></div><div class="cover-visual"><div class="cover-label">SELECTED WORK / AI에서 서비스까지</div><div class="cover-window"><div style="display:flex;justify-content:space-between;margin-bottom:16px"><b style="font-size:19px">HowToDo</b><span style="font-size:12px;color:#8b98a4">협업 사용설명서</span></div>${img('WebService/report-assets/ui-refresh/home-desktop.png','HowToDo 서비스 홈','')}</div><div class="cover-mini"><div><div class="ui-label">TEXT-TO-SQL · 저장된 실험</div><strong>32.2 → 96.7<small style="font-size:17px">%</small></strong><p>LoRA 전후 업무 규칙 준수율<br>학습 400 · 평가 20개</p><div class="mini-line"><i></i></div></div><div><div class="ui-label">ORDER BALANCE</div><strong>36 SKU</strong><p>판매 · 재고 · 발주 · 예산<br>데이터에서 발주 검토서로</p><div class="mini-line"><i style="width:100%;background:#298976"></i></div></div></div></div>`});
 slides.push({name:'프로젝트 한눈에 보기',html:`<div class="heading"><div><p class="eyebrow">SELECTED PROJECTS</p><h2 data-edit>정확도·일관성·속도·비용을 함께 보았습니다.</h2><p class="sub" data-edit>문제에 맞는 AI 방식과 서비스 구조를 선택하고, 결과를 확인할 수 있는 형태로 남겼습니다.</p></div></div><div class="index-grid">${[
 ['AI','근거와 판단을 설계하다','답변이 나오는 과정을 나누고<br>출력의 기준을 명확히 합니다.',[['Order Balance','발주 에이전트 · 계산과 설명 분리'],['Developer Prompt ER','질문 진단 · 구조화 출력 · 병렬 비교'],['PDF 문서 질의응답','pypdf · 임베딩 · FAISS 검색'],['Text-to-SQL / CNN','LoRA 학습 · 규칙 평가 · 학습 전략 비교']]],
 ['APP','사용 흐름을 완성하다','사용자가 입력하고 확인하고<br>다음 행동으로 이어가게 만듭니다.',[['웹툰 보이스 스튜디오','대사·캐릭터·음성 편집 화면 설계'],['QuizFlash / HowToDo','스트리밍 API · 협업 프로필·팀 보드'],['SKALA Shop','주문·취소 · 포인트·재고 트랜잭션'],['CourtCast / Weather Flow','현장 제보 · 날씨 · 즐겨찾기']]],
 ['OPS','측정하고 개선하다','응답 시간과 데이터 흐름을<br>운영 가능한 단위로 나눕니다.',[['GOLABA','서비스 경계 · REST/Kafka 설계 검토'],['3-tier 컨테이너 게시판','Compose · healthcheck · 데이터 지속성'],['매출 EDA 파이프라인','100만 행 데이터 정제·분석·학습'],['PostgreSQL 성능 튜닝','실행계획 · 인덱스 · 반복 측정']]]
 ].map(([n,t,d,items])=>`<article class="index-col"><span class="num">${n}</span><h3>${t}</h3><p>${d}</p>${items.map(([a,b])=>`<div class="index-item"><b>${a}</b><span>${b}</span></div>`).join('')}</article>`).join('')}</div>`});
 const helpers={project,img,badge,stats,table,flow,app,bar};
 aiProjects(helpers);webtoonProject(helpers);productProjects(helpers);
 slides.push({name:'제가 가져갈 설계 기준',class:'dark',html:`<div class="heading"><div><p class="eyebrow">DESIGN PRINCIPLES</p><h2 style="font-size:51px;line-height:1.25" data-edit>좋은 답변이,<br>다음 업무에서도 쓰일 수 있도록.</h2><p class="sub" style="margin-top:18px" data-edit>프로젝트를 통해 쌓은 네 가지 설계 기준입니다.</p></div></div><div class="closing-grid"><article><h3 data-edit>정확도 / 근거부터 확인합니다.</h3><p data-edit>검색이 찾은 정보와 모델이 만든 답을 구분하고,<br>데이터와 계산을 다시 확인할 수 있게 남깁니다.</p></article><article><h3 data-edit>일관성 / 출력의 약속을 만듭니다.</h3><p data-edit>필수 필드·자료형·판단 기준을 명시하고,<br>계산과 설명의 역할을 나눕니다.</p></article><article><h3 data-edit>속도 / 기다리는 구간을 나눕니다.</h3><p data-edit>병렬 생성·스트리밍·비동기 처리를 선택하고,<br>요청에서 표시까지의 지연을 측정합니다.</p></article><article><h3 data-edit>비용 / 필요한 문맥만 전달합니다.</h3><p data-edit>토큰과 호출을 기록하고, 역할별 데이터와<br>출력 범위를 줄일 수 있는 지점을 찾습니다.</p></article></div><div class="closing-author" data-edit>이 기준으로, 다음 AI 서비스를 설계하겠습니다.</div>`});
 slides.push({name:'GitHub · 프로젝트 링크',class:'github-slide',html:`<div class="github-heading"><div><p class="eyebrow">GITHUB / PROJECT DIRECTORY</p><h2 data-edit>코드와 설계를 직접 확인해 보세요.</h2><a class="github-profile" contenteditable="false" href="${githubProfile}" target="_blank" rel="noopener noreferrer">github.com/KR-Nom <span>↗</span></a></div><div class="github-intro"><b data-edit>장현진</b><p data-edit>AI 시스템 설계 · 모델 학습<br>서비스 구현 · 데이터 분석</p><a contenteditable="false" href="${portfolioRepository}" target="_blank" rel="noopener noreferrer">프로젝트 모음 저장소 ↗</a></div></div><div class="github-grid">${[
 ['AI · MODEL',['Order Balance · 발주 판단','Developer Prompt ER','PDF 문서 질의응답','Text-to-SQL · LoRA','CNN 구조와 과적합','QuizFlash · 스트리밍 API']],
 ['PRODUCT · INTERFACE',['웹툰 보이스 스튜디오','HowToDo · 협업 사용설명서','SKALA Shop · 주문과 데이터 정합성','CourtCast · 현장 제보와 코트 비교','Weather Flow · 날씨 대시보드','HONBOT·자율주행 · 학습 경험의 연결']],
 ['DATA · OPERATIONS',['GOLABA · 접수와 AI 검수의 분리','3-tier 게시판 · 컨테이너 실행','매출 EDA · 데이터에서 학습까지','PostgreSQL · 실행계획 기반 튜닝','AI 서비스 운영 · AIOps 확장 설계']]
 ].map(([group,names])=>`<div class="github-group"><h3>${group}</h3>${names.map(name=>{const l=projectLinks[name];return `<a class="github-item" contenteditable="false" href="${l.url}" target="_blank" rel="noopener noreferrer"><span><b>${l.label}</b><small>${l.path}</small></span><em>↗</em></a>`}).join('')}</div>`).join('')}</div>`});
 return {slides,evidence};
}
